# Generated by Django 4.2.2 on 2023-06-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=200)),
                ('familyasi', models.CharField(max_length=200)),
                ('fan_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maktabapp.fan')),
            ],
        ),
        migrations.CreateModel(
            name='Baholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maktabapp.fan')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maktabapp.student')),
            ],
        ),
    ]
